# Generated by Django 3.1.4 on 2022-06-13 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('esr21_reports', '0002_agestatistics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agestatistics',
            name='category',
        ),
    ]
