# Generated by Django 3.1.4 on 2022-06-13 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esr21_reports', '0004_auto_20220613_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccinationstatistics',
            name='dose_3',
            field=models.PositiveIntegerField(default=0, verbose_name='Booster Dose'),
        ),
        migrations.AlterField(
            model_name='agestatistics',
            name='lowerquartile',
            field=models.PositiveIntegerField(default=0, verbose_name='Lowerquartile'),
        ),
        migrations.AlterField(
            model_name='agestatistics',
            name='max',
            field=models.PositiveIntegerField(default=0, verbose_name='Max'),
        ),
        migrations.AlterField(
            model_name='agestatistics',
            name='median',
            field=models.PositiveIntegerField(default=0, verbose_name='Median'),
        ),
        migrations.AlterField(
            model_name='agestatistics',
            name='min',
            field=models.PositiveIntegerField(default=0, verbose_name='min'),
        ),
        migrations.AlterField(
            model_name='agestatistics',
            name='upperquartile',
            field=models.PositiveIntegerField(default=0, verbose_name='Upperquartile'),
        ),
        migrations.AlterField(
            model_name='vaccinationstatistics',
            name='dose_2',
            field=models.PositiveIntegerField(default=0, verbose_name='Second Dose'),
        ),
    ]
