# Generated by Django 3.1.4 on 2022-06-14 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esr21_reports', '0006_auto_20220613_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccinationstatistics',
            name='overall_percent',
            field=models.FloatField(default=0, verbose_name='Overall Percentage'),
        ),
        migrations.AlterField(
            model_name='vaccinationstatistics',
            name='dose_1_percent',
            field=models.FloatField(default=0, verbose_name='First Dose Percentage'),
        ),
        migrations.AlterField(
            model_name='vaccinationstatistics',
            name='dose_2_percent',
            field=models.FloatField(default=0, verbose_name='Second Dose Percentage'),
        ),
        migrations.AlterField(
            model_name='vaccinationstatistics',
            name='dose_3_percent',
            field=models.FloatField(default=0, verbose_name='Booster Dose Percentage'),
        ),
    ]
