# Generated by Django 3.1.4 on 2022-06-14 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esr21_reports', '0007_auto_20220614_0835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agestatistics',
            name='site',
            field=models.CharField(max_length=150, unique=True, verbose_name='Site'),
        ),
        migrations.AlterField(
            model_name='enrollmentstatistics',
            name='site',
            field=models.CharField(max_length=150, unique=True, verbose_name='Site'),
        ),
        migrations.AlterField(
            model_name='screeningstatistics',
            name='site',
            field=models.CharField(max_length=150, unique=True, verbose_name='Site'),
        ),
        migrations.AlterField(
            model_name='vaccinationstatistics',
            name='site',
            field=models.CharField(max_length=150, unique=True, verbose_name='Site'),
        ),
    ]
