# Generated by Django 3.1.4 on 2022-06-14 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esr21_reports', '0008_auto_20220614_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='agestatistics',
            name='outlier',
            field=models.PositiveIntegerField(default=0, verbose_name='Outliers'),
        ),
    ]
