# Generated by Django 3.1.4 on 2022-06-14 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esr21_reports', '0009_agestatistics_outlier'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardStatistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50)),
                ('value', models.TextField()),
            ],
        ),
    ]
